function importAll(r) {
    return r.keys().map(r);
}

const image = importAll(require.context('./', false, /\.(png|jpe?g|svg)$/));

const ImagesProducts = [
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
    {
        title: 'Sạc dự phòng không dây Magsafe Battettery Pack',
        image: image[0],
        to: 'sac-du-phong-khong-day-magsafe-battettery-pack',
        current: 'sacduphong',
        thuonghieu: 'apple',
        giamgia: 'Giảm 17%',
        mucgia: '2000000-4000000',
        price: '2.490.000₫',
        old_price: '2.990.000₫',
    },
    {
        title: 'Pencil',
        image: image[1],
        to: 'but-apple-penci',
        current: 'butpencil',
        thuonghieu: 'apple',
        giamgia: 'Giảm 18%',
        mucgia: '2000000-4000000',
        price: '3.290.000₫',
        old_price: '3.990.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 13 Pro Max',
        image: image[2],
        to: 'cuong-luc-kingbull-iphone-13-pro-max',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 10%',
        mucgia: '0_2000000',
        price: '350.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'Miếng dán cường lực Mipow Kingbull iPhone 11',
        image: image[2],
        to: 'kinh-cuong-luc-kingbull-iphone-11',
        current: 'cuongluc',
        thuonghieu: 'mipow',
        giamgia: 'Giảm 15%',
        mucgia: '0_2000000',
        price: '330.000₫',
        old_price: '390.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng chống nước 15000mAh (RP-PB124)',
        image: image[3],
        to: 'ravpower-sac-du-phong-chong-nuoc-15000mah-rp-pb124',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 4%',
        mucgia: '0_2000000',
        price: '1.050.000₫',
        old_price: '1.090.000₫',
    },
    {
        title: 'RAVPower Sạc dự phòng 10000mAh (RP-PB099)',
        image: image[4],
        to: 'ravpower-sac-du-phong-10000mah-rp-pb099',
        current: 'sacduphong',
        thuonghieu: 'ravpower',
        giamgia: 'Giảm 18%',
        mucgia: '0_2000000',
        price: '650.000₫',
        old_price: '790.000₫',
    },
    {
        title: 'Combo Ốp - Cường lực Jinya space protecting iPhone 12',
        image: image[5],
        to: 'combo-op-cuong-luc-jinya-space-protecting-iphone-12',
        current: 'cuongluc',
        thuonghieu: 'jinya',
        mucgia: '0_2000000',
        price: '250.000₫',
    },
];

export default ImagesProducts;
